int TOTAL_NUM_TASKS = 16000;
int NUM_WORKER_THREADS;
int caseParameter;
int NoOfRequestedNode;
int distribution;
int option;
int IncrementalUpdates;
int N;
char CSSize;
double threshold = 0.2;
double alpha = 0.5;
int maxRequestedNodes = 10000;
double degOfConc[32]; 
